### ISSUE TITLE
poold crashed and fails to start

### ISSUE THREAD

**Issue by ratpoison4** [lightninglabs/pool#176]
The crash after many hours of normal work and waiting for an order to be matched:

```
[INF] RPCS: Received new block notification: height=658351
[INF] RPCS: Received new block notification: height=658352
[INF] AUCT: Server is shutting down, will reconnect in 5s
[INF] AUCT: Successfully connected to auction server
[ERR] RPCS: Error in server stream: EOF
[ERR] AUCT: Error in stream, trying to reconnect: EOF
panic: close of closed channel

goroutine 58 [running]:
github.com/lightninglabs/pool/auctioneer.(*Client).closeStream(0xc0005a4100, 0x0, 0x0)
        /src/github.com/lightninglabs/pool/auctioneer/client.go:223 +0x194
github.com/lightninglabs/pool/auctioneer.(*Client).HandleServerShutdown(0xc0005a4100, 0x13a1ca0, 0xc000192050, 0xc00044e330, 0x1)
        /src/github.com/lightninglabs/pool/auctioneer/client.go:1035 +0xe5
github.com/lightninglabs/pool.(*rpcServer).serverHandler(0xc0005c02d0, 0xc0005a38c0, 0xc000160840)
        /src/github.com/lightninglabs/pool/rpcserver.go:321 +0x48e
created by github.com/lightninglabs/pool.(*rpcServer).Start
        /src/github.com/lightninglabs/pool/rpcserver.go:211 +0x9cf
```

Trying to start `poold` again fail:

```
$ poold
[INF] LLMD: Version: 0.3.3-alpha commit=
[INF] LNDC: Creating lnd connection to localhost:10009
[INF] LNDC: Connected to lnd
[INF] LNDC: lnd version: v0.11.1-beta, build tags 'autopilotrpc,signrpc,walletrpc,chainrpc,invoicesrpc,watchtowerrpc'
[INF] LNDC: Using network mainnet
[INF] LNDC: Waiting for lnd to be fully synced to its chain backend, this might take a while
[INF] LNDC: lnd is now fully synced to its chain backend
[INF] LLMD: Auction server address: pool.lightning.finance:12010
[INF] CLDB: Checking for schema update: latest_version=1, db_version=1
[INF] RPCS: Starting trader server
[INF] RPCS: Connected to lnd node [redacted] with pubkey [redacted]
[INF] ACCT: Watching spend of [redacted]:0 for account [redacted]
[INF] AUCT: Successfully connected to auction server
[INF] AUCT: Shutting down auctioneer client
[ERR] AUCT: [/poolrpc.ChannelAuctioneer/SubscribeBatchAuction]: rpc error: code = Canceled desc = context canceled
[ERR] ACCT: Unable to receive block notification: rpc error: code = Unavailable desc = transport is closing
unable to start server: unable to start account manager: unable to resume account [redacted]: unable to subscribe for account updates: EOF
```

Note: the mentioned UTXO (result of the order) is still not spent.

From LND logs when trying to start `poold`:

```
[INF] NTFN: New block epoch subscription
[INF] NTFN: New block epoch subscription
[DBG] NTFN: Using height hint [redacted, current BTC height] retrieved from cache for outpoint=[redacted]:0, script=0 [redacted] instead of [redacted,height of the utxo]
[INF] NTFN: New spend subscription: spend_id=33, outpoint=[redacted]:0, script=0 [redacted], height_hint=[redacted, current BTC height]
[DBG] NTFN: Attempting to dispatch spend for outpoint=[redacted]:0, script=0 [redacted] on registration since rescan has finished
[DBG] NTFN: Skipping dispatch of spend details(<nil>) for request outpoint=[redacted]:0, script=0 [redacted, unknown for me hash], dispatched=false
[INF] NTFN: Cancelling epoch notification, epoch_id=43
[INF] NTFN: Cancelling epoch notification, epoch_id=44
[ERR] RPCS: [/chainrpc.ChainNotifier/RegisterBlockEpochNtfn]: context canceled
[INF] NTFN: Canceling spend notification: spend_id=33, outpoint=[redacted]:0, script=0 [redacted, unknown for me hash]
[ERR] RPCS: [/chainrpc.ChainNotifier/RegisterSpendNtfn]: context canceled
[ERR] RPCS: [/chainrpc.ChainNotifier/RegisterBlockEpochNtfn]: context canceled
```

**Comment by Roasbeef** [comment]
Which version are you on?

**Comment by Roasbeef** [comment]
Also I take it that this is persistent and shows up each time you try to restart the node?

**Comment by ratpoison4** [comment]
```
$ poold --version
poold version 0.3.3-alpha commit=
```

Built from commit 7f4610096cb963c96b21f2bdc0bf57c59bffb401

> I take it that this is persistent and shows up each time you try to restart the node?

Yes

**Comment by qubenix** [comment]
I'm experiencing this exact same issue.

**Comment by guggero** [comment]
Thanks for the report, working on identifying the problem now.

**Comment by guggero** [comment]
I have a suspicion where the problem lies but wasn't able to confirm it yet.

@ratpoison4, @qubenix would any of you be willing to compile and run this version: https://github.com/guggero/pool/tree/account-fix
I added some additional information to our errors to better isolate the problem. Additionally, running with `--debuglevel=trace` and sending me the recent logs would also help a lot.

**Comment by ratpoison4** [comment]
@guggero I can do it. Please tell me where can I upload the logs. Please, can you give me your PGP key so that I could encrypt the logs and send them to your email (gugger@gmail.com)?

**Comment by guggero** [comment]
That would be great, thank you! My key is here: https://keybase.io/guggero/pgp_keys.asc
You can also contact me on our community Slack (https://lightning.engineering/slack.html), I have the same username and avatar there.

**Comment by guggero** [comment]
Thank you @ratpoison4 for helping with the debug process, a fix is now in review and an official client release will be published soon.
